const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILD: 'GET_ALL_USER_FAILD',

    //create new user
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_FAILD: 'CREATE_NEW_USER_FAILD',

    //delete user
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILD: 'DELETE_USER_FAILD',

    //edit user
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILD: 'EDIT_USER_FAILD',
    //edit user
    GET_USER_EDIT_SUCCESS: 'GET_USER_EDIT_SUCCESS',
    GET_USER_EDIT_FAILD: 'GET_USER_EDIT_FAILD',


    //crate Category
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILD: 'CREATE_CATEGORY_FAILD',
    //get all category
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILD: 'GET_ALL_CATEGORY_FAILD',
    //delete category
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILD: 'DELETE_CATEGORY_FAILD',
    //edit category
    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAILD: 'EDIT_CATEGORY_FAILD',

    //create new product
    CREATE_NEW_PRODUCT_SUCCESS: 'CREATE_NEW_PRODUCT_SUCCESS',
    CREATE_NEW_PRODUCT_FAILD: 'CREATE_NEW_PRODUCT_FAILD',

    //get all product
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILD: 'GET_ALL_PRODUCT_FAILD',
})

export default actionTypes;